### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by FolfyBlue** [C4illin/ASFclaim#35]
Hello, I am trying to use the docker for ASFclaim, but I am met with this error upon trying to run it:
```
asfclaim  | Only runs on the last 10 games
asfclaim  | Error: 
asfclaim  | {
asfclaim  |   Result: { Permanent: true, StatusCode: 401 },
asfclaim  |   Message: 'Failed!',
asfclaim  |   Success: false
asfclaim  | }
```
I believe this is because my IPC password is too big, or because it uses special characters (`*`, `!`, `^`, `@`, `%`, ...)

I'm not sure how this could be fixed (Maybe using an Authentication header instead of a query string? https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#authentication) but I really appreciate this project and hope somebody can look into this!

**Comment by C4illin** [comment]
Thanks for this! Could you test if it works now?

**Comment by FolfyBlue** [comment]
Sorry, I have since switched to hosting ASF on a Raspberry Pi but this project does not support the ARM architecture under Docker, so I cannot test or use this project anymore
