### ISSUE TITLE
Make it possible to specify which bots should try to add the licenses

### ISSUE THREAD

**Issue by floriegl** [C4illin/ASFclaim#70]
In ASF it's possible to specify which bots should be targeted by a command by listing them instead of just using ASF as the [Bots] arguments in the commands - see https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#bots-argument. Wouldn't it be useful to also expose this argument the same way as e.g., the commandprefix is configurable in .env, docker-compose.yml, ...?

**Comment by C4illin** [comment]
Yeah sure that is a good idea, I would not use it but I can see the use case. I think it will be very easy to add. Do you want to submit a PR?

**Comment by floriegl** [comment]
Yes, just testing it right now...
