### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by mgrimace** [C4illin/ASFclaim#8]
Hello, I gave this a try and receiving the following error:
```
~/ASFclaim$ node .
Only runs on the last 10 games
Error: 
{
  Result: { Permanent: true, StatusCode: 401 },
  Message: 'Failed!',
  Success: false
```
Any ideas for fixing? Thanks!

**Comment by mgrimace** [comment]
node -v `v18.5.0`
npm -v `8.13.2`

**Comment by mgrimace** [comment]
Yes, IPC seems to be working otherwise. It's running currently.

Additional details:
On a Ubuntu 20.04 virtual server, connected via SSH. ASF is running as a service, and I set it up so I can access the web-ui from my local computer. ASF is currently running with one bot online

I installed node using 
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs
```
then, just followed the instructions as-is:
`git clone https://github.com/C4illin/ASFclaim.git && cd ASFclaim`
`npm install`
`node .`

**Comment by Reajoan** [comment]
Open index.js and change :

**Comment by Reajoan** [comment]
Open index.js and change line 38
`fetch("http://localhost:1242/Api/Command", {`
To 
`fetch("http://localhost:1242/Api/Command?password=IPC_Password", {`
Make sure to change "IPC_Password" to your actual IPC login password.

**Comment by C4illin** [comment]
And you didn't change any IPC settings and no password?

**Comment by Rizwan-Mashfiq** [comment]
Its a Authentication Problem.
Open Index.js and change line 38
      `fetch("http://localhost:1242/Api/Command", {`
To
     `fetch("http://localhost:1242/Api/Command?password=your_password_here", {`
make sure to put your actual IPC password there instead of your_password_here
See https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#authentication

**Comment by Rizwan-Mashfiq** [comment]
Its a Authentication Problem.
Open Index.js and change line 38
fetch("http://localhost:1242/Api/Command", {
To
fetch("http://localhost:1242/Api/Command?password=your_password_here", {
Make sure to put your actual IPC password there instead of your_password_here.

**Comment by Rizwan-Mashfiq** [comment]
Its a Authentication Problem.
Open Index.js and change line 38
`fetch("http://localhost:1242/Api/Command", {`
To
`fetch("http://localhost:1242/Api/Command?password=your_password_here", {`
make sure to put your actual IPC password there instead of your_password_here

**Comment by mgrimace** [comment]
> Its a Authentication Problem.

Thanks, I'll give that a try, makes sense!

**Comment by C4illin** [comment]
@mgrimace did you figure it out?

**Comment by mgrimace** [comment]
@C4illin Sorry for the delay in testing/responding, yes the fix `fetch("http://localhost:1242/Api/Command?password=your_password_here", {` worked and it looks like it successfully claimed the last 10 games (or at least the ones I was eligible to claim)

```
node .
Only runs on the last 10 games
Success: !addlicense asf a/2067760,a/1846201,a/1846202,a/611360,s/749899,a/1211880,a/1908440,a/1164850,s/735409,a/317100
{
  Result: '<UbuntuBot> ID: app/2067760 | Status: OK | Items: app/2067760\n' +
    '<UbuntuBot> ID: app/1846201 | Status: OK\n' +
    '<UbuntuBot> ID: app/1846202 | Status: OK\n' +
    '<UbuntuBot> ID: app/611360 | Status: OK | Items: app/611360\n' +
    '<UbuntuBot> ID: sub/749899 | Status: AccessDenied/InvalidPackage\n' +
    '<UbuntuBot> ID: app/1211880 | Status: OK\n' +
    '<UbuntuBot> ID: app/1908440 | Status: OK\n' +
    '<UbuntuBot> ID: app/1164850 | Status: OK | Items: app/1164850\n' +
    '<UbuntuBot> ID: sub/735409 | Status: AccessDenied/InvalidPackage\n' +
    '<UbuntuBot> ID: app/317100 | Status: OK | Items: app/317100\n',
  Message: 'OK',
  Success: true
}

```
Thanks all
